package com.cp.bean;

import java.io.Serializable;

public class AllPeriod implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_all_period.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_all_period.yang_tm
     *
     * @mbg.generated
     */
    private String yangTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_all_period.yin_tm
     *
     * @mbg.generated
     */
    private String yinTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_all_period.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_all_period.year
     *
     * @mbg.generated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_all_period
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_all_period.id
     *
     * @return the value of t_all_period.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_all_period.id
     *
     * @param id the value for t_all_period.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_all_period.yang_tm
     *
     * @return the value of t_all_period.yang_tm
     *
     * @mbg.generated
     */
    public String getYangTm() {
        return yangTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_all_period.yang_tm
     *
     * @param yangTm the value for t_all_period.yang_tm
     *
     * @mbg.generated
     */
    public void setYangTm(String yangTm) {
        this.yangTm = yangTm == null ? null : yangTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_all_period.yin_tm
     *
     * @return the value of t_all_period.yin_tm
     *
     * @mbg.generated
     */
    public String getYinTm() {
        return yinTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_all_period.yin_tm
     *
     * @param yinTm the value for t_all_period.yin_tm
     *
     * @mbg.generated
     */
    public void setYinTm(String yinTm) {
        this.yinTm = yinTm == null ? null : yinTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_all_period.period
     *
     * @return the value of t_all_period.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_all_period.period
     *
     * @param period the value for t_all_period.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_all_period.year
     *
     * @return the value of t_all_period.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_all_period.year
     *
     * @param year the value for t_all_period.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }
}