package com.cp.bean;

import java.io.Serializable;
import java.util.Date;

public class BaseAnimal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.name_desc
     *
     * @mbg.generated
     */
    private String nameDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.color_desc
     *
     * @mbg.generated
     */
    private String colorDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.wuxing
     *
     * @mbg.generated
     */
    private String wuxing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.jiaye
     *
     * @mbg.generated
     */
    private String jiaye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.order
     *
     * @mbg.generated
     */
    private String order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_animal.create_tm
     *
     * @mbg.generated
     */
    private Date createTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.id
     *
     * @return the value of t_base_animal.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.id
     *
     * @param id the value for t_base_animal.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.name
     *
     * @return the value of t_base_animal.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.name
     *
     * @param name the value for t_base_animal.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.name_desc
     *
     * @return the value of t_base_animal.name_desc
     *
     * @mbg.generated
     */
    public String getNameDesc() {
        return nameDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.name_desc
     *
     * @param nameDesc the value for t_base_animal.name_desc
     *
     * @mbg.generated
     */
    public void setNameDesc(String nameDesc) {
        this.nameDesc = nameDesc == null ? null : nameDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.color
     *
     * @return the value of t_base_animal.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.color
     *
     * @param color the value for t_base_animal.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.color_desc
     *
     * @return the value of t_base_animal.color_desc
     *
     * @mbg.generated
     */
    public String getColorDesc() {
        return colorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.color_desc
     *
     * @param colorDesc the value for t_base_animal.color_desc
     *
     * @mbg.generated
     */
    public void setColorDesc(String colorDesc) {
        this.colorDesc = colorDesc == null ? null : colorDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.wuxing
     *
     * @return the value of t_base_animal.wuxing
     *
     * @mbg.generated
     */
    public String getWuxing() {
        return wuxing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.wuxing
     *
     * @param wuxing the value for t_base_animal.wuxing
     *
     * @mbg.generated
     */
    public void setWuxing(String wuxing) {
        this.wuxing = wuxing == null ? null : wuxing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.jiaye
     *
     * @return the value of t_base_animal.jiaye
     *
     * @mbg.generated
     */
    public String getJiaye() {
        return jiaye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.jiaye
     *
     * @param jiaye the value for t_base_animal.jiaye
     *
     * @mbg.generated
     */
    public void setJiaye(String jiaye) {
        this.jiaye = jiaye == null ? null : jiaye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.sex
     *
     * @return the value of t_base_animal.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.sex
     *
     * @param sex the value for t_base_animal.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.order
     *
     * @return the value of t_base_animal.order
     *
     * @mbg.generated
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.order
     *
     * @param order the value for t_base_animal.order
     *
     * @mbg.generated
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_animal.create_tm
     *
     * @return the value of t_base_animal.create_tm
     *
     * @mbg.generated
     */
    public Date getCreateTm() {
        return createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_animal.create_tm
     *
     * @param createTm the value for t_base_animal.create_tm
     *
     * @mbg.generated
     */
    public void setCreateTm(Date createTm) {
        this.createTm = createTm;
    }
}