package com.cp.bean;

import java.io.Serializable;
import java.util.Date;

public class BiyLottery implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diy_lottery.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diy_lottery.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diy_lottery.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diy_lottery.s_code
     *
     * @mbg.generated
     */
    private String sCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_diy_lottery.create_tm
     *
     * @mbg.generated
     */
    private Date createTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_diy_lottery
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diy_lottery.id
     *
     * @return the value of t_diy_lottery.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diy_lottery.id
     *
     * @param id the value for t_diy_lottery.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diy_lottery.period
     *
     * @return the value of t_diy_lottery.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diy_lottery.period
     *
     * @param period the value for t_diy_lottery.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diy_lottery.code
     *
     * @return the value of t_diy_lottery.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diy_lottery.code
     *
     * @param code the value for t_diy_lottery.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diy_lottery.s_code
     *
     * @return the value of t_diy_lottery.s_code
     *
     * @mbg.generated
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diy_lottery.s_code
     *
     * @param sCode the value for t_diy_lottery.s_code
     *
     * @mbg.generated
     */
    public void setsCode(String sCode) {
        this.sCode = sCode == null ? null : sCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_diy_lottery.create_tm
     *
     * @return the value of t_diy_lottery.create_tm
     *
     * @mbg.generated
     */
    public Date getCreateTm() {
        return createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_diy_lottery.create_tm
     *
     * @param createTm the value for t_diy_lottery.create_tm
     *
     * @mbg.generated
     */
    public void setCreateTm(Date createTm) {
        this.createTm = createTm;
    }
}