package com.cp.bean;

import java.io.Serializable;
import java.util.Date;

public class Lottery implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.begin_tm
     *
     * @mbg.generated
     */
    private Date beginTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.end_tm
     *
     * @mbg.generated
     */
    private Date endTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lottery
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.id
     *
     * @return the value of t_lottery.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.id
     *
     * @param id the value for t_lottery.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.period
     *
     * @return the value of t_lottery.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.period
     *
     * @param period the value for t_lottery.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.begin_tm
     *
     * @return the value of t_lottery.begin_tm
     *
     * @mbg.generated
     */
    public Date getBeginTm() {
        return beginTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.begin_tm
     *
     * @param beginTm the value for t_lottery.begin_tm
     *
     * @mbg.generated
     */
    public void setBeginTm(Date beginTm) {
        this.beginTm = beginTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.end_tm
     *
     * @return the value of t_lottery.end_tm
     *
     * @mbg.generated
     */
    public Date getEndTm() {
        return endTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.end_tm
     *
     * @param endTm the value for t_lottery.end_tm
     *
     * @mbg.generated
     */
    public void setEndTm(Date endTm) {
        this.endTm = endTm;
    }
}