package com.cp.bean;

import java.io.Serializable;
import java.util.Date;

public class Lottery implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.end_flag
     *
     * @mbg.generated
     */
    private String endFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.wuxing
     *
     * @mbg.generated
     */
    private String wuxing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.s_color
     *
     * @mbg.generated
     */
    private String sColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.jiaye
     *
     * @mbg.generated
     */
    private String jiaye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.s_head
     *
     * @mbg.generated
     */
    private String sHead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.s_dan_shuang
     *
     * @mbg.generated
     */
    private String sDanShuang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.s_tail
     *
     * @mbg.generated
     */
    private String sTail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.s_he
     *
     * @mbg.generated
     */
    private String sHe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.all_sum
     *
     * @mbg.generated
     */
    private String allSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.begin_tm
     *
     * @mbg.generated
     */
    private Date beginTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery.end_tm
     *
     * @mbg.generated
     */
    private Date endTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lottery
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.id
     *
     * @return the value of t_lottery.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.id
     *
     * @param id the value for t_lottery.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.period
     *
     * @return the value of t_lottery.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.period
     *
     * @param period the value for t_lottery.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.end_flag
     *
     * @return the value of t_lottery.end_flag
     *
     * @mbg.generated
     */
    public String getEndFlag() {
        return endFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.end_flag
     *
     * @param endFlag the value for t_lottery.end_flag
     *
     * @mbg.generated
     */
    public void setEndFlag(String endFlag) {
        this.endFlag = endFlag == null ? null : endFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.wuxing
     *
     * @return the value of t_lottery.wuxing
     *
     * @mbg.generated
     */
    public String getWuxing() {
        return wuxing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.wuxing
     *
     * @param wuxing the value for t_lottery.wuxing
     *
     * @mbg.generated
     */
    public void setWuxing(String wuxing) {
        this.wuxing = wuxing == null ? null : wuxing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.s_color
     *
     * @return the value of t_lottery.s_color
     *
     * @mbg.generated
     */
    public String getsColor() {
        return sColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.s_color
     *
     * @param sColor the value for t_lottery.s_color
     *
     * @mbg.generated
     */
    public void setsColor(String sColor) {
        this.sColor = sColor == null ? null : sColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.jiaye
     *
     * @return the value of t_lottery.jiaye
     *
     * @mbg.generated
     */
    public String getJiaye() {
        return jiaye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.jiaye
     *
     * @param jiaye the value for t_lottery.jiaye
     *
     * @mbg.generated
     */
    public void setJiaye(String jiaye) {
        this.jiaye = jiaye == null ? null : jiaye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.sex
     *
     * @return the value of t_lottery.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.sex
     *
     * @param sex the value for t_lottery.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.s_head
     *
     * @return the value of t_lottery.s_head
     *
     * @mbg.generated
     */
    public String getsHead() {
        return sHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.s_head
     *
     * @param sHead the value for t_lottery.s_head
     *
     * @mbg.generated
     */
    public void setsHead(String sHead) {
        this.sHead = sHead == null ? null : sHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.s_dan_shuang
     *
     * @return the value of t_lottery.s_dan_shuang
     *
     * @mbg.generated
     */
    public String getsDanShuang() {
        return sDanShuang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.s_dan_shuang
     *
     * @param sDanShuang the value for t_lottery.s_dan_shuang
     *
     * @mbg.generated
     */
    public void setsDanShuang(String sDanShuang) {
        this.sDanShuang = sDanShuang == null ? null : sDanShuang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.s_tail
     *
     * @return the value of t_lottery.s_tail
     *
     * @mbg.generated
     */
    public String getsTail() {
        return sTail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.s_tail
     *
     * @param sTail the value for t_lottery.s_tail
     *
     * @mbg.generated
     */
    public void setsTail(String sTail) {
        this.sTail = sTail == null ? null : sTail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.s_he
     *
     * @return the value of t_lottery.s_he
     *
     * @mbg.generated
     */
    public String getsHe() {
        return sHe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.s_he
     *
     * @param sHe the value for t_lottery.s_he
     *
     * @mbg.generated
     */
    public void setsHe(String sHe) {
        this.sHe = sHe == null ? null : sHe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.all_sum
     *
     * @return the value of t_lottery.all_sum
     *
     * @mbg.generated
     */
    public String getAllSum() {
        return allSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.all_sum
     *
     * @param allSum the value for t_lottery.all_sum
     *
     * @mbg.generated
     */
    public void setAllSum(String allSum) {
        this.allSum = allSum == null ? null : allSum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.begin_tm
     *
     * @return the value of t_lottery.begin_tm
     *
     * @mbg.generated
     */
    public Date getBeginTm() {
        return beginTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.begin_tm
     *
     * @param beginTm the value for t_lottery.begin_tm
     *
     * @mbg.generated
     */
    public void setBeginTm(Date beginTm) {
        this.beginTm = beginTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery.end_tm
     *
     * @return the value of t_lottery.end_tm
     *
     * @mbg.generated
     */
    public Date getEndTm() {
        return endTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery.end_tm
     *
     * @param endTm the value for t_lottery.end_tm
     *
     * @mbg.generated
     */
    public void setEndTm(Date endTm) {
        this.endTm = endTm;
    }
}