package com.cp.bean;

import java.io.Serializable;
import java.util.Date;

public class LotteryDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_detail.tl_id
     *
     * @mbg.generated
     */
    private Long tlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_detail.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_detail.order
     *
     * @mbg.generated
     */
    private String order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_detail.code_type
     *
     * @mbg.generated
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_detail.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_detail.create_tm
     *
     * @mbg.generated
     */
    private Date createTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lottery_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_detail.id
     *
     * @return the value of t_lottery_detail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_detail.id
     *
     * @param id the value for t_lottery_detail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_detail.tl_id
     *
     * @return the value of t_lottery_detail.tl_id
     *
     * @mbg.generated
     */
    public Long getTlId() {
        return tlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_detail.tl_id
     *
     * @param tlId the value for t_lottery_detail.tl_id
     *
     * @mbg.generated
     */
    public void setTlId(Long tlId) {
        this.tlId = tlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_detail.num
     *
     * @return the value of t_lottery_detail.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_detail.num
     *
     * @param num the value for t_lottery_detail.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_detail.order
     *
     * @return the value of t_lottery_detail.order
     *
     * @mbg.generated
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_detail.order
     *
     * @param order the value for t_lottery_detail.order
     *
     * @mbg.generated
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_detail.code_type
     *
     * @return the value of t_lottery_detail.code_type
     *
     * @mbg.generated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_detail.code_type
     *
     * @param codeType the value for t_lottery_detail.code_type
     *
     * @mbg.generated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_detail.color
     *
     * @return the value of t_lottery_detail.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_detail.color
     *
     * @param color the value for t_lottery_detail.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_detail.create_tm
     *
     * @return the value of t_lottery_detail.create_tm
     *
     * @mbg.generated
     */
    public Date getCreateTm() {
        return createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_detail.create_tm
     *
     * @param createTm the value for t_lottery_detail.create_tm
     *
     * @mbg.generated
     */
    public void setCreateTm(Date createTm) {
        this.createTm = createTm;
    }
}