package com.cp.bean;

import java.io.Serializable;

public class NumColor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_num_color.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_num_color.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_num_color.color
     *
     * @mbg.generated
     */
    private String color;

    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_num_color.color_desc
     *
     * @mbg.generated
     */
    private String colorDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_num_color.wuxing
     *
     * @mbg.generated
     */
    private String wuxing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_num_color
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_num_color.id
     *
     * @return the value of t_num_color.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_num_color.id
     *
     * @param id the value for t_num_color.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_num_color.num
     *
     * @return the value of t_num_color.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_num_color.num
     *
     * @param num the value for t_num_color.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_num_color.color
     *
     * @return the value of t_num_color.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_num_color.color
     *
     * @param color the value for t_num_color.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_num_color.color_desc
     *
     * @return the value of t_num_color.color_desc
     *
     * @mbg.generated
     */
    public String getColorDesc() {
        return colorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_num_color.color_desc
     *
     * @param colorDesc the value for t_num_color.color_desc
     *
     * @mbg.generated
     */
    public void setColorDesc(String colorDesc) {
        this.colorDesc = colorDesc == null ? null : colorDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_num_color.wuxing
     *
     * @return the value of t_num_color.wuxing
     *
     * @mbg.generated
     */
    public String getWuxing() {
        return wuxing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_num_color.wuxing
     *
     * @param wuxing the value for t_num_color.wuxing
     *
     * @mbg.generated
     */
    public void setWuxing(String wuxing) {
        this.wuxing = wuxing == null ? null : wuxing.trim();
    }

    public String getColorCode() {
        return colorCode;
    }

    public void setColorCode(String colorCode) {
        this.colorCode = colorCode;
    }
}