server:
  port: 9001

spring:
  mvc:
    static-path-pattern: /**
    view:
      prefix: /view
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
#      additional-paths: src/main/java
#      exclude: static/**,view/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  datasource:
    url: jdbc:mysql://rm-bp1p2241fb81mv31u1o.mysql.rds.aliyuncs.com:3306/cp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: cp
    password: 123++abc
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #禁止那些ip
        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true

mybatis:
  # model的包
  type-aliases-package: com.cp.dao
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true
    log-impl: null #打印结果集 org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:**/*Mapper.xml

# 配置pagehelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 打印sql
logging:
  level:
    com.cp.dao: debug

beetl:
  resource-auto-check: true #热加载beetl模板，开发时候用

# 图片的上传初始位置
#pic:
#  C:/A_MAO/futureimg/
pic:
  /tmp/image/

pic_ip:
  101.37.88.176

debug: true
