package com.cp.service;

import com.cp.dao.BaseMapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public abstract class BaseService<T,T1> {

    protected BaseMapper<T,T1> baseMapper;

    public abstract void initMapper();

    long countByExample(T example){
        return baseMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int deleteByExample(T example){
        return baseMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id){
        return baseMapper.deleteByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int insert(T1 record){
        return baseMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int insertSelective(T1 record){
        return baseMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    List<T1> selectByExample(T example){
        return baseMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    T1 selectByPrimaryKey(Long id){
        return baseMapper.selectByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") T1 record, @Param("example") T example){
        return baseMapper.updateByExampleSelective(record,example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") T1 record, @Param("example") T example){
        return baseMapper.updateByExample(record,example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(T1 record){
        return baseMapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_animal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T1 record){
        return baseMapper.updateByPrimaryKey(record);
    }
}
